import json, tiktoken, os, subprocess

enc = tiktoken.get_encoding("o200k_base")

def bench(label, json_path, llm_path, toon_path):
    with open(json_path) as f: data = json.load(f)
    with open(llm_path) as f: dx_llm = f.read()
    with open(toon_path) as f: toon_str = f.read()
    
    json_c = json.dumps(data, separators=(',', ':'))
    dx_wrapped = dx_llm  # Already generated by CLI
    # Also generate proper wrapped DF version manually
    def mk_wrapped(d, indent=0):
        lines = []
        for k, v in d.items():
            if isinstance(v, list) and v and isinstance(v[0], dict):
                fields = list(v[0].keys())
                lines.append(f"{k}[{' '.join(fields)}](")
                for item in v:
                    row = []
                    for f in fields:
                        val = item[f]
                        if isinstance(val, str) and ' ' in val: row.append(f'"{val}"')
                        elif isinstance(val, bool): row.append('true' if val else 'false')
                        elif val is None: row.append('null')
                        else: row.append(str(val))
                    lines.append(' '.join(row))
                lines.append(')')
            elif isinstance(v, list):
                items = []
                for x in v:
                    if isinstance(x, str) and ' ' in x: items.append(f'"{x}"')
                    elif isinstance(x, bool): items.append('true' if x else 'false')
                    elif x is None: items.append('null')
                    else: items.append(str(x))
                lines.append(f"{k}=[{' '.join(items)}]")
            elif isinstance(v, dict):
                parts = []
                for sk, sv in v.items():
                    s = f'"{sv}"' if isinstance(sv, str) and ' ' in sv else 'true' if sv is True else 'false' if sv is False else ('null' if sv is None else str(sv))
                    parts.append(f"{sk}={s}")
                lines.append(f"{k}({' '.join(parts)})")
            else:
                s = f'"{v}"' if isinstance(v, str) and ' ' in v else 'true' if v is True else 'false' if v is False else ('null' if v is None else str(v))
                lines.append(f"{k}={s}")
        return '\n'.join(lines) + '\n'
    
    dx_wrapped_str = mk_wrapped(data)
    
    print(f"\n{'='*75}")
    print(f"  {label}")
    print(f"{'='*75}")
    print(f"  {'Format':<30} {'Tokens':>8} {'Bytes':>8} {'vs JSON':>10}")
    print(f"  {'-'*56}")
    
    js_t = len(enc.encode(json_c))
    print(f"  {'JSON compact':<30} {js_t:>8} {len(json_c):>8} {'-':>10}")
    
    for name, txt in [
        ("DX LLM (CLI auto)", dx_llm),
        ("DX LLM (wrapped DF)", dx_wrapped_str),
        ("TOON (real spec)", toon_str),
    ]:
        t = len(enc.encode(txt))
        pct = (1 - t/js_t) * 100
        print(f"  {name:<30} {t:>8} {len(txt):>8} {f'{pct:+.1f}%':>10}")
    
    print(f"\n  --- TOON Output ---")
    print(toon_str.rstrip())

# Benchmark all
bench("SPEC EXAMPLE (from LLM_FORMAT_SPEC.md)", "sample.json", "sample-output/sample-json.llm", "sample-output/sample.toon")
bench("LARGE DATASET (21 deps + 10 team)", "sample_large.json", "sample-output/sample_large-json.llm", "sample-output/sample_large.toon")

# Also benchmark a 50-item table
big = {
    "project": "dx-serializer",
    "version": "1.0.0",
    "packages": [{"name": f"dep-{i}", "version": f"{i}.0.{i%5}", "enabled": i % 3 != 0} for i in range(50)]
}
json_c = json.dumps(big, separators=(',', ':'))
dx_wrapped_str = mk_wrapped(big)
enc2 = tiktoken.get_encoding("o200k_base")
js_t = len(enc2.encode(json_c))

# Generate TOON for 50-item
with open('_big50.json', 'w') as f: json.dump(big, f)

# Check if file was written
if os.path.exists('sample-output/big50.toon'):
    with open('sample-output/big50.toon') as f: toon_str = f.read()
    dx_t = len(enc2.encode(dx_wrapped_str))
    toon_t = len(enc2.encode(toon_str))
    print(f"\n{'='*75}")
    print(f"  50-ITEM TABLE")
    print(f"{'='*75}")
    print(f"  {'Format':<30} {'Tokens':>8} {'Bytes':>8} {'vs JSON':>10}")
    print(f"  {'-'*56}")
    print(f"  {'JSON compact':<30} {js_t:>8} {len(json_c):>8} {'-':>10}")
    print(f"  {'DX LLM (wrapped DF)':<30} {dx_t:>8} {len(dx_wrapped_str):>8} {(1-dx_t/js_t)*100:+.1f}%")
    print(f"  {'TOON (real spec)':<30} {toon_t:>8} {len(toon_str):>8} {(1-toon_t/js_t)*100:+.1f}%")
    print(f"\n  --- TOON Output ---")
    print(toon_str[:500])
